// 表情替换
export const emotionIcons = [
  {
    id: 1,
    name: "\\[笑哭\\]",
    type: "text",
    emoji: "😂",
    html_content: '<div style="display: inline; font-size: 16px;">😂</div>',
  },
  {
    id: 2,
    name: "\\[狗头\\]",
    type: "text",
    emoji: "🐶",
    html_content: '<div style="display: inline; font-size: 16px;">🐶</div>',
  },
  {
    id: 3,
    name: "\\[滑稽\\]",
    type: "text",
    emoji: "😏",
    html_content: '<div style="display: inline; font-size: 16px;">😏</div>',
  },
  {
    id: 4,
    name: "\\[吃瓜\\]",
    type: "text",
    emoji: "🧐",
    html_content: '<div style="display: inline; font-size: 16px;">🧐</div>',
  },
  {
    id: 5,
    name: "\\[惊呆\\]",
    type: "text",
    emoji: "🌚",
    html_content: '<div style="display: inline; font-size: 16px;">🌚</div>',
  },
  {
    id: 6,
    name: "\\[吐血\\]",
    type: "text",
    emoji: "😢",
    html_content: '<div style="display: inline; font-size: 16px;">😢</div>',
  },
  {
    id: 7,
    name: "\\[可怜\\]",
    type: "text",
    emoji: "🥺",
    html_content: '<div style="display: inline; font-size: 16px;">🥺</div>',
  },
  {
    id: 8,
    name: "\\[亲亲\\]",
    type: "text",
    emoji: "😚",
    html_content: '<div style="display: inline; font-size: 16px;">😚</div>',
  },
  {
    id: 9,
    name: "\\[大笑\\]",
    type: "text",
    emoji: "😄",
    html_content: '<div style="display: inline; font-size: 16px;">😄</div>',
  },
  {
    id: 10,
    name: "\\[龇牙\\]",
    type: "text",
    emoji: "😬",
    html_content: '<div style="display: inline; font-size: 16px;">😬</div>',
  },
  {
    id: 11,
    name: "\\[伤心\\]",
    type: "text",
    emoji: "😭",
    html_content: '<div style="display: inline; font-size: 16px;">😭</div>',
  },
  {
    id: 12,
    name: "\\[麻了\\]",
    type: "text",
    emoji: "🙄",
    html_content: '<div style="display: inline; font-size: 16px;">🙄</div>',
  },
  {
    id: 13,
    name: "\\[摸头\\]",
    type: "text",
    emoji: "😔",
    html_content: '<div style="display: inline; font-size: 16px;">😔</div>',
  },
  {
    id: 14,
    name: "\\[推眼镜\\]",
    type: "text",
    emoji: "😎",
    html_content: '<div style="display: inline; font-size: 16px;">😎</div>',
  },
  {
    id: 15,
    name: "\\[没眼看\\]",
    type: "text",
    emoji: "🙈",
    html_content: '<div style="display: inline; font-size: 16px;">🙈</div>',
  },
  {
    id: 16,
    name: "\\[功德\\]",
    type: "text",
    emoji: "🙏",
    html_content: '<div style="display: inline; font-size: 16px;">🙏</div>',
  },
  {
    id: 17,
    name: "\\[涩涩\\]",
    type: "text",
    emoji: "😍",
    html_content: '<div style="display: inline; font-size: 16px;">😍</div>',
  },
  {
    id: 18,
    name: "\\[色色\\]",
    type: "text",
    emoji: "🥵",
    html_content: '<div style="display: inline; font-size: 16px;">🥵</div>',
  },
  {
    id: 19,
    name: "\\[禁止色色\\]",
    type: "text",
    emoji: "💩",
    html_content: '<div style="display: inline; font-size: 16px;">💩</div>',
  },
  {
    id: 20,
    name: "\\[头秃\\]",
    type: "text",
    emoji: "🚬",
    html_content: '<div style="display: inline; font-size: 16px;">🚬</div>',
  },
  {
    id: 21,
    name: "\\[庆祝\\]",
    type: "text",
    emoji: "🥳",
    html_content: '<div style="display: inline; font-size: 16px;">🥳</div>',
  },
  {
    id: 22,
    name: "\\[点赞\\]",
    type: "text",
    emoji: "👍",
    html_content: '<div style="display: inline; font-size: 16px;">👍</div>',
  },
  {
    id: 23,
    name: "\\[加油\\]",
    type: "text",
    emoji: "💪",
    html_content: '<div style="display: inline; font-size: 16px;">💪</div>',
  },
  {
    id: 24,
    name: "\\[祈福\\]",
    type: "text",
    emoji: "🙏",
    html_content: '<div style="display: inline; font-size: 16px;">🙏</div>',
  },
  {
    id: 25,
    name: "\\[疑问\\]",
    type: "text",
    emoji: "🤔",
    html_content: '<div style="display: inline; font-size: 16px;">🤔</div>',
  },
  {
    id: 26,
    name: "\\[哼\\]",
    type: "text",
    emoji: "😤",
    html_content: '<div style="display: inline; font-size: 16px;">😤</div>',
  },
  // {
  //   id: 27,
  //   name: "\\[尴尬\\]",
  //   type: "text",
  //   emoji: "",
  //   html_content: '<div style="display: inline; font-size: 16px;">🐶</div>',
  // },
  {
    id: 28,
    name: "\\[叹气\\]",
    type: "text",
    emoji: "🤕",
    html_content: '<div style="display: inline; font-size: 16px;">🤕</div>',
  },
  {
    id: 29,
    name: "\\[愤怒\\]",
    type: "text",
    emoji: "😡",
    html_content: '<div style="display: inline; font-size: 16px;">😡</div>',
  },
  {
    id: 30,
    name: "\\[小丑\\]",
    type: "text",
    emoji: "🤡",
    html_content: '<div style="display: inline; font-size: 16px;">🤡</div>',
  },
  {
    id: 31,
    name: "\\[人品\\]",
    type: "text",
    emoji: "💟",
    html_content: '<div style="display: inline; font-size: 16px;">💟</div>',
  },
  {
    id: 32,
    name: "\\[分\\]",
    type: "text",
    emoji: "💔",
    html_content: '<div style="display: inline; font-size: 16px;">💔</div>',
  },
  {
    id: 33,
    name: "\\[喝阔落\\]",
    type: "text",
    emoji: "😌",
    html_content: '<div style="display: inline; font-size: 16px;">😌</div>',
  },
  {
    id: 34,
    name: "\\[白眼\\]",
    type: "text",
    emoji: "🙄",
    html_content: '<div style="display: inline; font-size: 16px;">🙄</div>',
  },
  {
    id: 35,
    name: "\\[开心\\]",
    type: "text",
    emoji: "😊",
    html_content: '<div style="display: inline; font-size: 16px;">😊</div>',
  },
  {
    id: 36,
    name: "\\[投降\\]",
    type: "text",
    emoji: "🙃",
    html_content: '<div style="display: inline; font-size: 16px;">🙃</div>',
  },
  {
    id: 37,
    name: "\\[稽滑\\]",
    type: "text",
    emoji: "😏",
    html_content: '<div style="display: inline; font-size: 16px;">😏</div>',
  },
  {
    id: 38,
    name: "\\[三花\\]",
    type: "text",
    emoji: "😼",
    html_content: '<div style="display: inline; font-size: 16px;">😼</div>',
  },
  {
    id: 39,
    name: "\\[比心\\]",
    type: "text",
    emoji: "😘",
    html_content: '<div style="display: inline; font-size: 16px;">😘</div>',
  },
  {
    id: 40,
    name: "\\[苦涩\\]",
    type: "text",
    emoji: "😅",
    html_content: '<div style="display: inline; font-size: 16px;">😅</div>',
  },
  {
    id: 41,
    name: "\\[激动\\]",
    type: "text",
    emoji: "🥰",
    html_content: '<div style="display: inline; font-size: 16px;">🥰</div>',
  },
];
